name: Drupal project CI demo
on: [push]
jobs:
  drupal-codebase-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.lock
        uses: php-actions/composer@v6
        with:
          command: composer validate --no-check-all --no-check-publish
